err

diff --git a/.github/workflows/changelog.yaml b/.github/workflows/changelog.yaml
--- a/.github/workflows/changelog.yaml
+++ b/.github/workflows/changelog.yaml
@@ -24,7 +24,8 @@ jobs:
       run: |
         pr_number=$(gh pr list --base $RELEASE_BRANCH | grep $PRERELEASE_BRANCH | cut -f 1)
         if [ -z $pr_number ]; then
-          exit 0
+          echo "not found pre-release PR"
+          exit 1
         fi
 
         echo "::set-output name=pr_number::$pr_number"
